{
 "title": "Network",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ],
      [
       { "params": [ "lon" ], "type": "field" }
      ],
      [
       { "params": [ "locality_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Localities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT count(distinct(\"locality_name\")) FROM \"weather\"",
     "select": [
      [
       { "params": [ "locality_name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AVG temp every 1 hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT MEAN(\"temp\") - 273.15 FROM \"weather\" GROUP BY time(1h) LIMIT 24",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature °C",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temp\") - 273.15 FROM \"weather\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Quality",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Mbits", "label": "Speed" }
   ],
   "targets": [
    {
     "alias": "Ping (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Download (Mbps)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload (Mbps)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "4h Avg Download (Mbps)",
     "groupBy": [
      { "params": [ "4h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}